#!/bin/bash
# name is where to store Matlab eeg file
name=/tmp/imagenet40-1000/imagenet40-1000
# dir is where to store the pytorch model .ph file
dir=/fs/aux/qobi/eeg-datasets/imagenet40-1000/preprocessed-no-z-score/imagenet40-1000
rm -rf /tmp/imagenet40-1000
mkdir /tmp/imagenet40-1000
rm -rf /fs/aux/qobi/eeg-datasets/imagenet40-1000/preprocessed-no-z-score/
mkdir /fs/aux/qobi/eeg-datasets/imagenet40-1000/preprocessed-no-z-score/
for subject in 1; do
    mkdir $name-$subject
done
cd ~/eeg-experiments/imagenet40-1000/bin-no-z-score/
matlab -nosplash -nodesktop -r "preprocessing"
for subject in 1; do
    python split_even.py\
           -iv image\
	   -s big\
	   -p $name-$subject\
	   -n $dir-$subject.pth\
           -stimuli image.txt\
	   -f 5
done
rm -rf /tmp/imagenet40-1000
