#!/bin/bash

subject=1
DIR=/aux/qobi/eeg-datasets/imagenet40-1000/preprocessed/imagenet40-1000
kind=from-scratch

rm -f SyncNet.pkl
rm -f *.pyc

unbuff >SyncNet.txt python main_loop.py \
       -iv image\
       -rf SyncNet.pkl \
       -s $subject \
       -r "imagenet40-1000" \
       -ed $DIR-$subject.pth \
       -sp $DIR-${subject}_split.pth \
       -f 5 \
       -c SyncNet \
       -gpu 7 \
       -k $kind&
